server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: ops
    password: ops2024.
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://127.0.0.1:3306/ops?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.op.des.web.dao.po # 给pojo实体类起别名
  mapper-locations: classpath:com/op/des/web/dao/mapper/*.xml # 接口的配置文件的位置 我这里接口配置文件是UserMapper.xml

private:
  key: djafo&*&(988*T*


wechat:
  pay:
    mchId: 1608048750
    privateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzlFQm5qdk5GVHM4Qk4KTERCL3VKTno4UWFYV1ZzaG1iallpZyswd1NKNGxnMzZtbStraHNCVkNabE45dDdzb2VaT2FELzczOXhrTVphZApPbVdEaFBoSFlIVStxUmh4TEd1MjNwODFiTVVNMyttSUhWNTd5RjRVUTllZDBvVVhpb1NjSU13L3VCTTk0ZzhHCmFEZkdJcE9qMHlaVEZIenlIZFpHaEtpYWZxSFhtL2ZZR1d3cmJpTDEzWE82M0xBcEFsQS9QQ0J6Zm5mdEM5amgKb2NDd2JjK1BudTdJSHkyLzBkbGozcnkrMEVYZWdPL3hkZUdBN2UyWXhXN080bzg0d2ZEMEpsM0lDWGQwNFRaRQp2K0ljbG9KM0tEN0lpZXZadFM4MldwQXgxeDkvVFlaaXNVcEdlZkhHWVlpTTZ5cEpHYTlHcVQwbU5zS1JrcDYvCkI0VytJS3R6QWdNQkFBRUNnZ0VBTEpPTFJ5TFJ5QVp0cE1SeWV1cXQrWHd1cmFpbnovaEttT09VYUczUkR0VnkKWGsvaldzdGF0YklacjBReHMyRkl4OXZVbWpKaDZFMjQwVUZmaGU3b0N3dzNHSnNONUVFdzlHRHc4TXZBZWhTaApIekt0Z0VueHhKMXFUUS9CeVpjalJSeUdpODkrMmV4ZTFvZmovcGRRY0NQc3VWSHZVN2F0T3RzMFZaamQxOVBLCmdVTGdaUDNvc0ZNUHdZa3llaC90R3F6YVhzVWoybmNOVk1TcGNDaTltMHFQeWp4L1NRZVJody95V3FKMFl2YzMKTWY2U1hnZkVVMzZWZjdwblBaN3FFY0Q5YUpsR0duN2lBbHQ2RWY5MDBEUDFDem8wdExSRFIxa3FFUkdEU2dnawpoQ3EreGh3OHB0R0dtTkQ3SzNCT1NDUHVGT25vTFBUazBkWGw1QTJKQVFLQmdRRGo1V1hDZzl5eU5hK1A0QVQ0Ck12bmhBc2pvd3ZTTkwrRTJHNUh6YTEzaGh2cmJ5anZ1NkdhQ1ZIdThLSXdaSDRUQ1FvZzd2VTZEZVlsOGdRSWkKUm1CVi8wL3VyVWRoZDYrOVN5Y3FOSzVOMmxieFpXMVAybEd0RldTU3doS3BvUGFiM0FidGtnOVUzYldVb2NqdgpTZUtHTWtsTXNsZHNKcmw1Y25VVXNLQWkwd0tCZ1FEVVlNREJ0bkRPMFJVSm5tT01Ld0pJd2ErallsazdRMkdDCnM3eitqNVJmcjVKVVFSU1hXa0UzWitZUGRIU1JZdUJ4SURoa3oxRXRYV25KNkZwaEJKSGExRkNWUCtRYWtNSjIKWHJNV0x1eEVoZUFnUlY1N2l5S3lZU3MvVm9hTy9nYWZDaWdvM2gzVHFjL1krV09Cb2k1elhFNmJKa1ZQQTVVTwpwK201TUN1dzRRS0JnUUNYb2swQkRlZk1rN2dLelEzQmIzbWY0OUIyUHpHa3Q1VHNBWkF0SE9WTWFCbUdJSnVjCkxQbjRBZXFLbVpnT0oxQ1lTTmlJbHo4a2I3dXhJYzJmckovdzJINEEyejdCZFhkelJndjdJeTVQRXRZQ3JHLzkKVDlCRWtCVnBLTVJ1SlhHdzVzZWRUeS93VWN5OTVwL2h4NUYzcFFIc2pFVnE2cUZDVTR2ZmhsNG1qUUtCZ1FERQpYMm9jTTh0L0VFajVpZURXSEhhU083Vmh4M0Jtb2RrcDkzUUxsVXRHWnB0UkdKUW5scWF5eW5rcFZTN3J0NWQ4ClFxU2lZaWZYWUlhTzBTK3dnWDh6N2hsTXg3VHM4Mms3OWpoMWpKR2Vrb000azZ2WFpFR0MydUlZUUxOT3lJZnEKeW9OenRsMng5MVJlZGNxU2RSbXFSWEhSZDhPaVdkZWJvNXN6UnQwL1FRS0JnSFpBM1FFcjNJNlM1NEg2dk50dQp4azVsVkpib294VTlMUmRqanlCL0tWY3pJbExubi9taVhRaCszUW51RGNtS3RGaFpjczFyK0ZPMU1vMGl6MUx4Cjdqc0ZzS1NNRE01OUpUYUlqZmVtcTROb2MySDV5dTdZZEFWbjlLakhFN3Q0dXpja2JpQUE3d3FsLzlVN1pjY1EKT3JXY29nSDBXREtNUlVVUENaV3RmVnZoCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    merchantSerialNumber: 35BE58D115677D8ECB47A0801DB459486261B0F6
    apiV3key: Z3p6cHN4c2JyYmxtZHN6and5amtkeXFrRTEyMzQ1Njc=
    appId: wx53f9a69d037df999

  callback:
    notifyUrl: https://152.136.43.219/op/des/order/notify


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

