server:
  port: 8080

spring:
  datasource:
    username: root
    password: kun123
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://127.0.0.1:3306/pos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.op.des.web.dao.po # 给pojo实体类起别名
  mapper-locations: classpath:mapper/*.xml # 接口的配置文件的位置 我这里接口配置文件是UserMapper.xml