package com.op.des.web.dao.po;

import java.io.Serializable;

public class BaZiTiYaoPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bazitiyao.id
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bazitiyao.zhi_month
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private String zhiMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bazitiyao.zhi_day
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private String zhiDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bazitiyao.zhi_time
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private String zhiTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bazitiyao.content
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bazitiyao.id
     *
     * @return the value of bazitiyao.id
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bazitiyao.id
     *
     * @param id the value for bazitiyao.id
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bazitiyao.zhi_month
     *
     * @return the value of bazitiyao.zhi_month
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public String getZhiMonth() {
        return zhiMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bazitiyao.zhi_month
     *
     * @param zhiMonth the value for bazitiyao.zhi_month
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public void setZhiMonth(String zhiMonth) {
        this.zhiMonth = zhiMonth == null ? null : zhiMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bazitiyao.zhi_day
     *
     * @return the value of bazitiyao.zhi_day
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public String getZhiDay() {
        return zhiDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bazitiyao.zhi_day
     *
     * @param zhiDay the value for bazitiyao.zhi_day
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public void setZhiDay(String zhiDay) {
        this.zhiDay = zhiDay == null ? null : zhiDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bazitiyao.zhi_time
     *
     * @return the value of bazitiyao.zhi_time
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public String getZhiTime() {
        return zhiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bazitiyao.zhi_time
     *
     * @param zhiTime the value for bazitiyao.zhi_time
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public void setZhiTime(String zhiTime) {
        this.zhiTime = zhiTime == null ? null : zhiTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bazitiyao.content
     *
     * @return the value of bazitiyao.content
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bazitiyao.content
     *
     * @param content the value for bazitiyao.content
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", zhiMonth=").append(zhiMonth);
        sb.append(", zhiDay=").append(zhiDay);
        sb.append(", zhiTime=").append(zhiTime);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BaZiTiYaoPO other = (BaZiTiYaoPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getZhiMonth() == null ? other.getZhiMonth() == null : this.getZhiMonth().equals(other.getZhiMonth()))
            && (this.getZhiDay() == null ? other.getZhiDay() == null : this.getZhiDay().equals(other.getZhiDay()))
            && (this.getZhiTime() == null ? other.getZhiTime() == null : this.getZhiTime().equals(other.getZhiTime()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getZhiMonth() == null) ? 0 : getZhiMonth().hashCode());
        result = prime * result + ((getZhiDay() == null) ? 0 : getZhiDay().hashCode());
        result = prime * result + ((getZhiTime() == null) ? 0 : getZhiTime().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}