package com.op.des.web.dao.po;

import java.util.ArrayList;
import java.util.List;

public class BookInfoPOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public BookInfoPOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNull() {
            addCriterion("book_name is null");
            return (Criteria) this;
        }

        public Criteria andBookNameIsNotNull() {
            addCriterion("book_name is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameEqualTo(String value) {
            addCriterion("book_name =", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotEqualTo(String value) {
            addCriterion("book_name <>", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThan(String value) {
            addCriterion("book_name >", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameGreaterThanOrEqualTo(String value) {
            addCriterion("book_name >=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThan(String value) {
            addCriterion("book_name <", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLessThanOrEqualTo(String value) {
            addCriterion("book_name <=", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameLike(String value) {
            addCriterion("book_name like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotLike(String value) {
            addCriterion("book_name not like", value, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameIn(List<String> values) {
            addCriterion("book_name in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotIn(List<String> values) {
            addCriterion("book_name not in", values, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameBetween(String value1, String value2) {
            addCriterion("book_name between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookNameNotBetween(String value1, String value2) {
            addCriterion("book_name not between", value1, value2, "bookName");
            return (Criteria) this;
        }

        public Criteria andBookLogoIsNull() {
            addCriterion("book_logo is null");
            return (Criteria) this;
        }

        public Criteria andBookLogoIsNotNull() {
            addCriterion("book_logo is not null");
            return (Criteria) this;
        }

        public Criteria andBookLogoEqualTo(String value) {
            addCriterion("book_logo =", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoNotEqualTo(String value) {
            addCriterion("book_logo <>", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoGreaterThan(String value) {
            addCriterion("book_logo >", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoGreaterThanOrEqualTo(String value) {
            addCriterion("book_logo >=", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoLessThan(String value) {
            addCriterion("book_logo <", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoLessThanOrEqualTo(String value) {
            addCriterion("book_logo <=", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoLike(String value) {
            addCriterion("book_logo like", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoNotLike(String value) {
            addCriterion("book_logo not like", value, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoIn(List<String> values) {
            addCriterion("book_logo in", values, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoNotIn(List<String> values) {
            addCriterion("book_logo not in", values, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoBetween(String value1, String value2) {
            addCriterion("book_logo between", value1, value2, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookLogoNotBetween(String value1, String value2) {
            addCriterion("book_logo not between", value1, value2, "bookLogo");
            return (Criteria) this;
        }

        public Criteria andBookDetailIsNull() {
            addCriterion("book_detail is null");
            return (Criteria) this;
        }

        public Criteria andBookDetailIsNotNull() {
            addCriterion("book_detail is not null");
            return (Criteria) this;
        }

        public Criteria andBookDetailEqualTo(String value) {
            addCriterion("book_detail =", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailNotEqualTo(String value) {
            addCriterion("book_detail <>", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailGreaterThan(String value) {
            addCriterion("book_detail >", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailGreaterThanOrEqualTo(String value) {
            addCriterion("book_detail >=", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailLessThan(String value) {
            addCriterion("book_detail <", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailLessThanOrEqualTo(String value) {
            addCriterion("book_detail <=", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailLike(String value) {
            addCriterion("book_detail like", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailNotLike(String value) {
            addCriterion("book_detail not like", value, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailIn(List<String> values) {
            addCriterion("book_detail in", values, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailNotIn(List<String> values) {
            addCriterion("book_detail not in", values, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailBetween(String value1, String value2) {
            addCriterion("book_detail between", value1, value2, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookDetailNotBetween(String value1, String value2) {
            addCriterion("book_detail not between", value1, value2, "bookDetail");
            return (Criteria) this;
        }

        public Criteria andBookPathIsNull() {
            addCriterion("book_path is null");
            return (Criteria) this;
        }

        public Criteria andBookPathIsNotNull() {
            addCriterion("book_path is not null");
            return (Criteria) this;
        }

        public Criteria andBookPathEqualTo(String value) {
            addCriterion("book_path =", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathNotEqualTo(String value) {
            addCriterion("book_path <>", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathGreaterThan(String value) {
            addCriterion("book_path >", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathGreaterThanOrEqualTo(String value) {
            addCriterion("book_path >=", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathLessThan(String value) {
            addCriterion("book_path <", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathLessThanOrEqualTo(String value) {
            addCriterion("book_path <=", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathLike(String value) {
            addCriterion("book_path like", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathNotLike(String value) {
            addCriterion("book_path not like", value, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathIn(List<String> values) {
            addCriterion("book_path in", values, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathNotIn(List<String> values) {
            addCriterion("book_path not in", values, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathBetween(String value1, String value2) {
            addCriterion("book_path between", value1, value2, "bookPath");
            return (Criteria) this;
        }

        public Criteria andBookPathNotBetween(String value1, String value2) {
            addCriterion("book_path not between", value1, value2, "bookPath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}