package com.op.des.web.dao.po;

import java.io.Serializable;

public class BookInfoPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.book_logo
     *
     * @mbg.generated
     */
    private String bookLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.book_detail
     *
     * @mbg.generated
     */
    private String bookDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookinfo.book_path
     *
     * @mbg.generated
     */
    private String bookPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.id
     *
     * @return the value of bookinfo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.id
     *
     * @param id the value for bookinfo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.book_name
     *
     * @return the value of bookinfo.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.book_name
     *
     * @param bookName the value for bookinfo.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.book_logo
     *
     * @return the value of bookinfo.book_logo
     *
     * @mbg.generated
     */
    public String getBookLogo() {
        return bookLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.book_logo
     *
     * @param bookLogo the value for bookinfo.book_logo
     *
     * @mbg.generated
     */
    public void setBookLogo(String bookLogo) {
        this.bookLogo = bookLogo == null ? null : bookLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.book_detail
     *
     * @return the value of bookinfo.book_detail
     *
     * @mbg.generated
     */
    public String getBookDetail() {
        return bookDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.book_detail
     *
     * @param bookDetail the value for bookinfo.book_detail
     *
     * @mbg.generated
     */
    public void setBookDetail(String bookDetail) {
        this.bookDetail = bookDetail == null ? null : bookDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookinfo.book_path
     *
     * @return the value of bookinfo.book_path
     *
     * @mbg.generated
     */
    public String getBookPath() {
        return bookPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookinfo.book_path
     *
     * @param bookPath the value for bookinfo.book_path
     *
     * @mbg.generated
     */
    public void setBookPath(String bookPath) {
        this.bookPath = bookPath == null ? null : bookPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bookName=").append(bookName);
        sb.append(", bookLogo=").append(bookLogo);
        sb.append(", bookDetail=").append(bookDetail);
        sb.append(", bookPath=").append(bookPath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BookInfoPO other = (BookInfoPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBookName() == null ? other.getBookName() == null : this.getBookName().equals(other.getBookName()))
            && (this.getBookLogo() == null ? other.getBookLogo() == null : this.getBookLogo().equals(other.getBookLogo()))
            && (this.getBookDetail() == null ? other.getBookDetail() == null : this.getBookDetail().equals(other.getBookDetail()))
            && (this.getBookPath() == null ? other.getBookPath() == null : this.getBookPath().equals(other.getBookPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBookName() == null) ? 0 : getBookName().hashCode());
        result = prime * result + ((getBookLogo() == null) ? 0 : getBookLogo().hashCode());
        result = prime * result + ((getBookDetail() == null) ? 0 : getBookDetail().hashCode());
        result = prime * result + ((getBookPath() == null) ? 0 : getBookPath().hashCode());
        return result;
    }
}