package com.op.des.web.dao.po;

import java.io.Serializable;

public class ChengGuSuanMingPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chenggusuanming.id
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chenggusuanming.sex
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chenggusuanming.gu_weight
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private String guWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chenggusuanming.ming_detail
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private String mingDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chenggusuanming.comment
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chenggusuanming.id
     *
     * @return the value of chenggusuanming.id
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chenggusuanming.id
     *
     * @param id the value for chenggusuanming.id
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chenggusuanming.sex
     *
     * @return the value of chenggusuanming.sex
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chenggusuanming.sex
     *
     * @param sex the value for chenggusuanming.sex
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chenggusuanming.gu_weight
     *
     * @return the value of chenggusuanming.gu_weight
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public String getGuWeight() {
        return guWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chenggusuanming.gu_weight
     *
     * @param guWeight the value for chenggusuanming.gu_weight
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setGuWeight(String guWeight) {
        this.guWeight = guWeight == null ? null : guWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chenggusuanming.ming_detail
     *
     * @return the value of chenggusuanming.ming_detail
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public String getMingDetail() {
        return mingDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chenggusuanming.ming_detail
     *
     * @param mingDetail the value for chenggusuanming.ming_detail
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setMingDetail(String mingDetail) {
        this.mingDetail = mingDetail == null ? null : mingDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chenggusuanming.comment
     *
     * @return the value of chenggusuanming.comment
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chenggusuanming.comment
     *
     * @param comment the value for chenggusuanming.comment
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sex=").append(sex);
        sb.append(", guWeight=").append(guWeight);
        sb.append(", mingDetail=").append(mingDetail);
        sb.append(", comment=").append(comment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChengGuSuanMingPO other = (ChengGuSuanMingPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getGuWeight() == null ? other.getGuWeight() == null : this.getGuWeight().equals(other.getGuWeight()))
            && (this.getMingDetail() == null ? other.getMingDetail() == null : this.getMingDetail().equals(other.getMingDetail()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getGuWeight() == null) ? 0 : getGuWeight().hashCode());
        result = prime * result + ((getMingDetail() == null) ? 0 : getMingDetail().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        return result;
    }
}