package com.op.des.web.dao.po;

import java.util.ArrayList;
import java.util.List;

public class ChengGuSuanMingPOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public ChengGuSuanMingPOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Byte> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Byte> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andGuWeightIsNull() {
            addCriterion("gu_weight is null");
            return (Criteria) this;
        }

        public Criteria andGuWeightIsNotNull() {
            addCriterion("gu_weight is not null");
            return (Criteria) this;
        }

        public Criteria andGuWeightEqualTo(String value) {
            addCriterion("gu_weight =", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightNotEqualTo(String value) {
            addCriterion("gu_weight <>", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightGreaterThan(String value) {
            addCriterion("gu_weight >", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightGreaterThanOrEqualTo(String value) {
            addCriterion("gu_weight >=", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightLessThan(String value) {
            addCriterion("gu_weight <", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightLessThanOrEqualTo(String value) {
            addCriterion("gu_weight <=", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightLike(String value) {
            addCriterion("gu_weight like", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightNotLike(String value) {
            addCriterion("gu_weight not like", value, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightIn(List<String> values) {
            addCriterion("gu_weight in", values, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightNotIn(List<String> values) {
            addCriterion("gu_weight not in", values, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightBetween(String value1, String value2) {
            addCriterion("gu_weight between", value1, value2, "guWeight");
            return (Criteria) this;
        }

        public Criteria andGuWeightNotBetween(String value1, String value2) {
            addCriterion("gu_weight not between", value1, value2, "guWeight");
            return (Criteria) this;
        }

        public Criteria andMingDetailIsNull() {
            addCriterion("ming_detail is null");
            return (Criteria) this;
        }

        public Criteria andMingDetailIsNotNull() {
            addCriterion("ming_detail is not null");
            return (Criteria) this;
        }

        public Criteria andMingDetailEqualTo(String value) {
            addCriterion("ming_detail =", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailNotEqualTo(String value) {
            addCriterion("ming_detail <>", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailGreaterThan(String value) {
            addCriterion("ming_detail >", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailGreaterThanOrEqualTo(String value) {
            addCriterion("ming_detail >=", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailLessThan(String value) {
            addCriterion("ming_detail <", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailLessThanOrEqualTo(String value) {
            addCriterion("ming_detail <=", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailLike(String value) {
            addCriterion("ming_detail like", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailNotLike(String value) {
            addCriterion("ming_detail not like", value, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailIn(List<String> values) {
            addCriterion("ming_detail in", values, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailNotIn(List<String> values) {
            addCriterion("ming_detail not in", values, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailBetween(String value1, String value2) {
            addCriterion("ming_detail between", value1, value2, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andMingDetailNotBetween(String value1, String value2) {
            addCriterion("ming_detail not between", value1, value2, "mingDetail");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chenggusuanming
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 11 13:49:50 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}