package com.op.des.web.dao.po;

import java.io.Serializable;

public class QuJiLunPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qujilun.id
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qujilun.tiangan
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private String tiangan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qujilun.sex
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qujilun.special_name
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private String specialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qujilun.introduction
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qujilun.id
     *
     * @return the value of qujilun.id
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qujilun.id
     *
     * @param id the value for qujilun.id
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qujilun.tiangan
     *
     * @return the value of qujilun.tiangan
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public String getTiangan() {
        return tiangan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qujilun.tiangan
     *
     * @param tiangan the value for qujilun.tiangan
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public void setTiangan(String tiangan) {
        this.tiangan = tiangan == null ? null : tiangan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qujilun.sex
     *
     * @return the value of qujilun.sex
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qujilun.sex
     *
     * @param sex the value for qujilun.sex
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qujilun.special_name
     *
     * @return the value of qujilun.special_name
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public String getSpecialName() {
        return specialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qujilun.special_name
     *
     * @param specialName the value for qujilun.special_name
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public void setSpecialName(String specialName) {
        this.specialName = specialName == null ? null : specialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qujilun.introduction
     *
     * @return the value of qujilun.introduction
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qujilun.introduction
     *
     * @param introduction the value for qujilun.introduction
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tiangan=").append(tiangan);
        sb.append(", sex=").append(sex);
        sb.append(", specialName=").append(specialName);
        sb.append(", introduction=").append(introduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuJiLunPO other = (QuJiLunPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTiangan() == null ? other.getTiangan() == null : this.getTiangan().equals(other.getTiangan()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getSpecialName() == null ? other.getSpecialName() == null : this.getSpecialName().equals(other.getSpecialName()))
            && (this.getIntroduction() == null ? other.getIntroduction() == null : this.getIntroduction().equals(other.getIntroduction()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTiangan() == null) ? 0 : getTiangan().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getSpecialName() == null) ? 0 : getSpecialName().hashCode());
        result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
        return result;
    }
}