package com.op.des.web.dao.po;

import java.io.Serializable;

public class UserInfoPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pasw
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String pasw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.birthday
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.birthaddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String birthaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.currentAddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private String currentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pasw
     *
     * @return the value of userinfo.pasw
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getPasw() {
        return pasw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pasw
     *
     * @param pasw the value for userinfo.pasw
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setPasw(String pasw) {
        this.pasw = pasw == null ? null : pasw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.birthday
     *
     * @return the value of userinfo.birthday
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.birthday
     *
     * @param birthday the value for userinfo.birthday
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.birthaddress
     *
     * @return the value of userinfo.birthaddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getBirthaddress() {
        return birthaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.birthaddress
     *
     * @param birthaddress the value for userinfo.birthaddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setBirthaddress(String birthaddress) {
        this.birthaddress = birthaddress == null ? null : birthaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.currentAddress
     *
     * @return the value of userinfo.currentAddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.currentAddress
     *
     * @param currentaddress the value for userinfo.currentAddress
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress == null ? null : currentaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", pasw=").append(pasw);
        sb.append(", phone=").append(phone);
        sb.append(", sex=").append(sex);
        sb.append(", birthday=").append(birthday);
        sb.append(", age=").append(age);
        sb.append(", birthaddress=").append(birthaddress);
        sb.append(", currentaddress=").append(currentaddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfoPO other = (UserInfoPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPasw() == null ? other.getPasw() == null : this.getPasw().equals(other.getPasw()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getBirthaddress() == null ? other.getBirthaddress() == null : this.getBirthaddress().equals(other.getBirthaddress()))
            && (this.getCurrentaddress() == null ? other.getCurrentaddress() == null : this.getCurrentaddress().equals(other.getCurrentaddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPasw() == null) ? 0 : getPasw().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getBirthaddress() == null) ? 0 : getBirthaddress().hashCode());
        result = prime * result + ((getCurrentaddress() == null) ? 0 : getCurrentaddress().hashCode());
        return result;
    }
}