package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.ArticlePO;
import com.op.des.web.dao.po.ArticlePOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    long countByExample(ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int deleteByExample(ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int insert(ArticlePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int insertSelective(ArticlePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    List<ArticlePO> selectByExampleWithBLOBs(ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    List<ArticlePO> selectByExample(ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    ArticlePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByExampleSelective(@Param("record") ArticlePO record, @Param("example") ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") ArticlePO record, @Param("example") ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByExample(@Param("record") ArticlePO record, @Param("example") ArticlePOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByPrimaryKeySelective(ArticlePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ArticlePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Sun Jul 28 20:18:43 CST 2024
     */
    int updateByPrimaryKey(ArticlePO record);
}