package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.BaZiTiYaoPO;
import com.op.des.web.dao.po.BaZiTiYaoPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaZiTiYaoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    long countByExample(BaZiTiYaoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int deleteByExample(BaZiTiYaoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int insert(BaZiTiYaoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int insertSelective(BaZiTiYaoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    List<BaZiTiYaoPO> selectByExample(BaZiTiYaoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    BaZiTiYaoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int updateByExampleSelective(@Param("record") BaZiTiYaoPO record, @Param("example") BaZiTiYaoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int updateByExample(@Param("record") BaZiTiYaoPO record, @Param("example") BaZiTiYaoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int updateByPrimaryKeySelective(BaZiTiYaoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bazitiyao
     *
     * @mbg.generated Sun Aug 11 13:35:05 CST 2024
     */
    int updateByPrimaryKey(BaZiTiYaoPO record);
}