package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.BookInfoPO;
import com.op.des.web.dao.po.BookInfoPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    long countByExample(BookInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int deleteByExample(BookInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int insert(BookInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int insertSelective(BookInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    List<BookInfoPO> selectByExample(BookInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    BookInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BookInfoPO record, @Param("example") BookInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BookInfoPO record, @Param("example") BookInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookInfoPO record);
}