package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.ChengGuSuanMingPO;
import com.op.des.web.dao.po.ChengGuSuanMingPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChengGuSuanMingPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    long countByExample(ChengGuSuanMingPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int deleteByExample(ChengGuSuanMingPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int insert(ChengGuSuanMingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int insertSelective(ChengGuSuanMingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    List<ChengGuSuanMingPO> selectByExample(ChengGuSuanMingPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    ChengGuSuanMingPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int updateByExampleSelective(@Param("record") ChengGuSuanMingPO record, @Param("example") ChengGuSuanMingPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int updateByExample(@Param("record") ChengGuSuanMingPO record, @Param("example") ChengGuSuanMingPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int updateByPrimaryKeySelective(ChengGuSuanMingPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chenggusuanming
     *
     * @mbg.generated Sun Aug 11 13:49:50 CST 2024
     */
    int updateByPrimaryKey(ChengGuSuanMingPO record);
}