package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.GongWeiLunPO;
import com.op.des.web.dao.po.GongWeiLunPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GongWeiLunPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    long countByExample(GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int deleteByExample(GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int insert(GongWeiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int insertSelective(GongWeiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    List<GongWeiLunPO> selectByExampleWithBLOBs(GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    List<GongWeiLunPO> selectByExample(GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    GongWeiLunPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByExampleSelective(@Param("record") GongWeiLunPO record, @Param("example") GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") GongWeiLunPO record, @Param("example") GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByExample(@Param("record") GongWeiLunPO record, @Param("example") GongWeiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByPrimaryKeySelective(GongWeiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(GongWeiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongweilun
     *
     * @mbg.generated Mon Oct 07 11:15:15 CST 2024
     */
    int updateByPrimaryKey(GongWeiLunPO record);
}