package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.OrderInfoPO;
import com.op.des.web.dao.po.OrderInfoPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    long countByExample(OrderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int deleteByExample(OrderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int insert(OrderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int insertSelective(OrderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    List<OrderInfoPO> selectByExample(OrderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    OrderInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderInfoPO record, @Param("example") OrderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderInfoPO record, @Param("example") OrderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderInfoPO record);
}