package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.orderInfoPO;
import com.op.des.web.dao.po.orderInfoPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orderInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    long countByExample(orderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int deleteByExample(orderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int insert(orderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int insertSelective(orderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    List<orderInfoPO> selectByExample(orderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    orderInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") orderInfoPO record, @Param("example") orderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") orderInfoPO record, @Param("example") orderInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(orderInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(orderInfoPO record);
}