package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.QuJiLunPO;
import com.op.des.web.dao.po.QuJiLunPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuJiLunPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    long countByExample(QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int deleteByExample(QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int insert(QuJiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int insertSelective(QuJiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    List<QuJiLunPO> selectByExampleWithBLOBs(QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    List<QuJiLunPO> selectByExample(QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    QuJiLunPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByExampleSelective(@Param("record") QuJiLunPO record, @Param("example") QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") QuJiLunPO record, @Param("example") QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByExample(@Param("record") QuJiLunPO record, @Param("example") QuJiLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByPrimaryKeySelective(QuJiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(QuJiLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qujilun
     *
     * @mbg.generated Mon Oct 07 11:40:16 CST 2024
     */
    int updateByPrimaryKey(QuJiLunPO record);
}