package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.RiZhuLunPO;
import com.op.des.web.dao.po.RiZhuLunPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RiZhuLunPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    long countByExample(RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int deleteByExample(RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int insert(RiZhuLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int insertSelective(RiZhuLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    List<RiZhuLunPO> selectByExampleWithBLOBs(RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    List<RiZhuLunPO> selectByExample(RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    RiZhuLunPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByExampleSelective(@Param("record") RiZhuLunPO record, @Param("example") RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") RiZhuLunPO record, @Param("example") RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByExample(@Param("record") RiZhuLunPO record, @Param("example") RiZhuLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByPrimaryKeySelective(RiZhuLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(RiZhuLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rizhulun
     *
     * @mbg.generated Mon Oct 07 11:14:20 CST 2024
     */
    int updateByPrimaryKey(RiZhuLunPO record);
}