package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.ShenShaLunPO;
import com.op.des.web.dao.po.ShenShaLunPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShenShaLunPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    long countByExample(ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int deleteByExample(ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int insert(ShenShaLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int insertSelective(ShenShaLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    List<ShenShaLunPO> selectByExampleWithBLOBs(ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    List<ShenShaLunPO> selectByExample(ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    ShenShaLunPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByExampleSelective(@Param("record") ShenShaLunPO record, @Param("example") ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") ShenShaLunPO record, @Param("example") ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByExample(@Param("record") ShenShaLunPO record, @Param("example") ShenShaLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByPrimaryKeySelective(ShenShaLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ShenShaLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shenshalun
     *
     * @mbg.generated Mon Oct 07 11:38:41 CST 2024
     */
    int updateByPrimaryKey(ShenShaLunPO record);
}