package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.UserInfoPO;
import com.op.des.web.dao.po.UserInfoPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    long countByExample(UserInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int deleteByExample(UserInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int insert(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int insertSelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    List<UserInfoPO> selectByExample(UserInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    UserInfoPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserInfoPO record, @Param("example") UserInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int updateByExample(@Param("record") UserInfoPO record, @Param("example") UserInfoPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int updateByPrimaryKeySelective(UserInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Sun Oct 06 11:28:33 CST 2024
     */
    int updateByPrimaryKey(UserInfoPO record);
}