package com.op.des.web.dao.mapper;

import com.op.des.web.dao.po.XingShenLunPO;
import com.op.des.web.dao.po.XingShenLunPOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XingShenLunPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    long countByExample(XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int deleteByExample(XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int insert(XingShenLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int insertSelective(XingShenLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    List<XingShenLunPO> selectByExampleWithBLOBs(XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    List<XingShenLunPO> selectByExample(XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    XingShenLunPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByExampleSelective(@Param("record") XingShenLunPO record, @Param("example") XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") XingShenLunPO record, @Param("example") XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByExample(@Param("record") XingShenLunPO record, @Param("example") XingShenLunPOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByPrimaryKeySelective(XingShenLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(XingShenLunPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xingshenlun
     *
     * @mbg.generated Mon Oct 07 11:38:08 CST 2024
     */
    int updateByPrimaryKey(XingShenLunPO record);
}